import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Fredoka } from 'next/font/google'
import next from 'next'
import './globals.css'

import Button from './ui/Button'

const inter = Inter({ subsets: ['latin'] })
const fredoka = Fredoka({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='h-full'>
      <body className={`${fredoka.className} font-bold h-full`}>
        <header className='h-16 bg-themed-blue text-white flex place-content-between items-center p-4'>
          <h1 className='font-bold'>NINTENDO GAME FINDER</h1>
          <div className='flex'>
            <div className='border-r-2 px-4'>Log In</div>
            <div className='px-4'>Sign In</div>
          </div>
        </header>
        <div className='flex h-full w-full'>
          <aside className='flex flex-col p-6 w-64 bg-aside-gray'>
            <Button text='MANAGE ROOMS' />
          </aside>
          <main className='w-full p-4 pt-4'>{children}</main>
        </div>
      </body>
    </html>
  )
}
