import type { Metadata } from "next"
import { Fredoka } from "next/font/google"
import Link from "next/link"
import "../globals.css"

const fredoka = Fredoka({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Nintendo Game Finder",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${fredoka.className} font-bold h-screen relative`}>
        <header className='h-16 bg-themed-blue text-white bg-sky-500 flex place-content-between items-center p-4'>
          <Link href='/'>
            <h1 className='font-bold'>NINTENDO GAME FINDER</h1>
          </Link>
          <div className='flex'>
            <Link href='/login' className='border-r-2 px-4'>
              <h2>Log In</h2>
            </Link>
            <Link href='/signup' className='px-4'>
              <h2>Sign Up</h2>
            </Link>
          </div>
        </header>
        <div className='flex'>
          <main className='flex flex-col p-4 pt-4 mx-20'>{children}</main>
        </div>
        <div
          id='form-modal'
          className='absolute left-1/2 bottom-1/2 z-1000'
        ></div>
      </body>
    </html>
  )
}
