import type { Metadata } from "next"
import { Fredoka } from "next/font/google"
import "../globals.css"

const fredoka = Fredoka({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Nintendo Game Finder",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${fredoka.className} font-bold h-screen relative`}>
        {children}
      </body>
    </html>
  )
}
